name = "cloudflare-hono-lucia-auth"
compatibility_date = "2023-12-01"

[[d1_databases]]
database_id = "ba017be7-82c3-48b4-a8d8-82b437b9f711"
binding = "DB"
database_name = "cloudflare-hono-lucia-auth"
